version: '3'

services:
  web:
    build:
      context: .   # Use the current directory as the build context
    ports:
      - "${APP_PORT}:80"  # Define the external and internal port mapping
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db1

  db1:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3430:3306"
